Repository ItaloRamirezA/G1-TiendaOnline, pull requests merged in 2024-12, with the labels that each got.

#9 creación diseño de página #1
  index.html
Labels: Feature

#13 Style terminado, fondo y productos agregados
  images/Peluches.jpg
  images/cerdo.png
  images/fondo.png
  images/ocelote.png
  images/peluches.png
  index.html
  styles.css
Labels: enhancement, Feature

#14 Funciones agregadas, avance style pero falta el carrito y algunos cambios en html #3
  index.html
  script.js
  styles.css
Labels: enhancement

#15 Avance metodo de agrearAlCarrito #4
  index.html
  script.js
Labels: enhancement

#21 metodoActualizarCarrito
  script.js
Labels: Feature

#22 metodoActualizarCarrito
  script.js
Labels: Feature

#23 Issue #10] información en readme
  README.md
Labels: documentation, Feature
